services:
  - type: web
    name: cea-viz
    env: node
    region: singapore
    plan: free
    buildCommand: |
      cd backend && \
      npm install && \
      npm run build && \
      cd ../frontend && \
      npm install && \
      npm run build
    startCommand: cd backend && npm run server
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        sync: false
