services:
  - type: web
    name: cea-viz
    env: node
    region: singapore
    plan: free
    buildCommand: git lfs install && git lfs pull && make build
    startCommand: make start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        sync: false
